name = "alicesaidhi/conch"
version = "0.2.0-rc.3"
description = "Modern command library for Roblox"
authors = ["alicesaidhi"]
repository = "https://github.com/alicesaidhi/conch"
license = "MIT"

workspace_members = ["pkgs/*"]

[target]
environment = "roblox"

[scripts]
roblox_sync_config_generator = ".pesde/roblox_sync_config_generator.luau"
sourcemap_generator = ".pesde/sourcemap_generator.luau"

[indices]
default = "https://github.com/daimond113/pesde-index"

[wally_indices]
default = "https://github.com/UpliftGames/wally-index"