column_width = 100
line_endings = "Unix"
indent_type = "Tabs"
indent_with = 4
quote_style = "AutoPreferDouble"
collapse_simple_statement = "InputOnly"
call_parentheses = "Input"

[sort_requires]
enabled = true
