name = "alicesaidhi/conch_ui"
version = "0.1.0"

[target]
environment = "roblox"
lib = "src/init.luau"

[indices]
default = "https://github.com/daimond113/pesde-index"

[wally_indices]
default = "https://github.com/UpliftGames/wally-index"

[scripts]
roblox_sync_config_generator = ".pesde/roblox_sync_config_generator.luau"
sourcemap_generator = ".pesde/sourcemap_generator.luau"

[dependencies]
vide = { wally = "wally#centau/vide", version = "^0.3.1" }
ast = { workspace = "alicesaidhi/conch_ast", version = "^", target = "luau" }
conch_glue = { workspace = "alicesaidhi/conch_glue", version = "^" }
