name = "alicesaidhi/conch_types"
version = "0.1.0"

[target]
environment = "roblox"
lib = "src/lib.luau"
build_files = ["src/lib.luau"]

[indices]
default = "https://github.com/daimond113/pesde-index"

[dependencies]
