name = "alicesaidhi/conch_types"
version = "0.2.0-rc.1"

[target]
environment = "luau"
lib = "src/lib.luau"
build_files = ["src/lib.luau"]

[indices]
default = "https://github.com/daimond113/pesde-index"

[dependencies]
