name = "alicesaidhi/conch_ast"
version = "0.2.0-rc.1"

[target]
environment = "luau"
lib = "src/lib.luau"
build_files = ["src/"]

[indices]
default = "https://github.com/daimond113/pesde-index"

[dependencies]
types = { workspace = "alicesaidhi/conch_types", version = "^" }